[book]
authors = ["Craig Hill"]
language = "en"
multilingual = false
src = "src"
title = "Zettelkasten Refactoring - Craig Hill"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-css = ["theme/custom.css"]
mathjax-support = true
disable-dark-theme = true

[output.html.playground]
editable = true
